/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.PatientDirectory;
import Data.DoctorDirectory;
import Data.HospitalDirectory;
import Model.Doctor;
import Model.Patient;
import Model.MedSystem;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HemaSree Bojanapally
 */
public class GetDoctorsForm extends javax.swing.JPanel {

    /**
     * Creates new form GetDotorsForm
     */
    MedSystem ms;
    String patientName;
        
    public GetDoctorsForm(MedSystem ms, String patientName) {
        this.ms = ms;
        this.patientName = patientName;
        initComponents();
        Patient patient = getPatient(patientName);
        displayDoctors(patient);
    }

    private Patient getPatient(String patientName) {
        for(Patient p:ms.getPatientList().getPatients()) {
            if(p.getFullName().equals(patientName))
                return p;
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        doctorsList = new javax.swing.JScrollPane();
        tblDoctors = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        tblDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor", "Hospital", "Community"
            }
        ));
        doctorsList.setViewportView(tblDoctors);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doctorsList, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(doctorsList, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void displayDoctors(Patient patient) {
        if(patient == null)
            return;
        
        String patientCommunity = patient.getResidence().getCommunity().getCommunity();
        
        
        DefaultTableModel model = (DefaultTableModel)tblDoctors.getModel();
        for(Doctor d:ms.getDoctorList().getDoctors()) {
            if(d.getHospital().getCommunity().equals(patientCommunity)) {
                Object[] row = new Object [3];
                row[0] = d.getDoctorName();
                row[1] = d.getHospital().getHospitalName();
                row[2] = d.getHospital().getCommunity();
                model.addRow(row);
            }  
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane doctorsList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tblDoctors;
    // End of variables declaration//GEN-END:variables
}
